services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "3010:3010"

    environment:
      NODE_ENV: production
      PORT: 3010

    networks:
      - web

networks:
  web:
    driver: bridge
