import type {
  ClinicListItem,
  DoctorListItem,
  ReviewItem,
  ServiceItem,
} from "../dummies/mocks";

export const MOCK_DOCTORS: DoctorListItem[] = [
  {
    id: "1",
    name: "Токтосунова Айгуль Бекова",
    specialty: "Кардиолог",
    isOnlineAvailable: true,
    rating: 4.9,
    reviews: 134,
    experience: 12,
    image: "https://pravatar.cc/300?img=47",
    education:
      "КГМА им. И.К. Ахунбаева, 2012. Ординатура по кардиологии — Москва, РНИМУ, 2014.",
    about:
      "Специализируется на лечении ишемической болезни сердца, гипертонии и нарушений ритма. Владеет ЭхоКГ и холтеровским мониторированием.",
    workplaces: [
      {
        clinicId: "1",
        clinicName: "МЦ «Медика»",
        price: 1500,
        schedule: {
          mon: { start: "09:00", end: "18:00" },
          tue: { start: "09:00", end: "18:00" },
          wed: null,
          thu: { start: "09:00", end: "18:00" },
          fri: { start: "09:00", end: "17:00" },
          sat: null,
          sun: null,
          lunchBreak: { start: "13:00", end: "14:00" },
        },
      },
      {
        clinicId: "4",
        clinicName: "МЦ «Жизнь»",
        price: 1800,
        schedule: {
          mon: null,
          tue: null,
          wed: { start: "10:00", end: "16:00" },
          thu: null,
          fri: null,
          sat: { start: "10:00", end: "14:00" },
          sun: null,
          lunchBreak: null,
        },
      },
    ],
    skills: ["ЭКГ", "ЭхоКГ", "Холтер", "Суточное АД", "Велоэргометрия"],
    contacts: {
      schedule: "Пн, Вт, Чт, Пт: 09:00–18:00",
      phone: "+996 700 123 456",
      email: "toktosunova@medika.kg",
    },
  },
  {
    id: "2",
    name: "Алиев Марат Жапарович",
    specialty: "Терапевт",
    isOnlineAvailable: true,
    rating: 4.7,
    reviews: 210,
    experience: 8,
    image: "https://pravatar.cc/300?img=12",
    education: "ОшГМА, 2016. Специализация по внутренним болезням.",
    about:
      "Врач общей практики. Проводит комплексные обследования, лечение ОРВИ, бронхитов, гастритов и других терапевтических заболеваний.",
    workplaces: [
      {
        clinicId: "1",
        clinicName: "МЦ «Медика»",
        price: 900,
        schedule: {
          mon: { start: "08:00", end: "17:00" },
          tue: { start: "08:00", end: "17:00" },
          wed: { start: "08:00", end: "17:00" },
          thu: { start: "08:00", end: "17:00" },
          fri: { start: "08:00", end: "16:00" },
          sat: null,
          sun: null,
          lunchBreak: { start: "12:00", end: "13:00" },
        },
      },
    ],
    skills: ["Диагностика", "УЗИ брюшной полости", "Спирометрия"],
    contacts: {
      schedule: "Пн–Пт: 08:00–17:00",
      phone: "+996 700 234 567",
      email: "aliev@medika.kg",
    },
  },
  {
    id: "3",
    name: "Исакова Гульнара Турдуевна",
    specialty: "Невролог",
    isOnlineAvailable: false,
    rating: 4.8,
    reviews: 88,
    experience: 15,
    image: "https://pravatar.cc/300?img=25",
    education: "КГМА, 2009. Ординатура по неврологии — Санкт-Петербург, 2011.",
    about:
      "Занимается лечением мигреней, остеохондроза, инсультов и эпилепсии. Большой опыт в нейрореабилитации.",
    workplaces: [
      {
        clinicId: "1",
        clinicName: "МЦ «Медика»",
        price: 1400,
        schedule: {
          mon: { start: "09:00", end: "17:00" },
          tue: null,
          wed: { start: "09:00", end: "17:00" },
          thu: null,
          fri: { start: "09:00", end: "17:00" },
          sat: null,
          sun: null,
          lunchBreak: { start: "13:00", end: "14:00" },
        },
      },
    ],
    skills: ["ЭЭГ", "ЭНМГ", "МРТ-навигация", "Рефлексотерапия"],
    contacts: {
      schedule: "Пн, Ср, Пт: 09:00–17:00",
      phone: "+996 700 345 678",
      email: "isakova@medika.kg",
    },
  },
  {
    id: "4",
    name: "Мамытов Бакыт Эркинович",
    specialty: "Педиатр",
    isOnlineAvailable: true,
    rating: 4.9,
    reviews: 302,
    experience: 10,
    image: "https://pravatar.cc/300?img=33",
    education: "КГМА, 2014. Ординатура по педиатрии.",
    about:
      "Детский врач с широким опытом в лечении инфекционных и соматических заболеваний у детей от 0 до 18 лет.",
    workplaces: [
      {
        clinicId: "4",
        clinicName: "МЦ «Жизнь»",
        price: 1100,
        schedule: {
          mon: { start: "09:00", end: "18:00" },
          tue: { start: "09:00", end: "18:00" },
          wed: { start: "09:00", end: "18:00" },
          thu: { start: "09:00", end: "18:00" },
          fri: { start: "09:00", end: "17:00" },
          sat: { start: "10:00", end: "14:00" },
          sun: null,
          lunchBreak: { start: "13:00", end: "14:00" },
        },
      },
    ],
    skills: ["Вакцинация", "Грудное вскармливание", "Аллергология"],
    contacts: {
      schedule: "Пн–Сб: 09:00–18:00",
      phone: "+996 700 456 789",
      email: "mamytov@zhizn.kg",
    },
  },
  {
    id: "5",
    name: "Джумабекова Анара Сатыбековна",
    specialty: "Дерматолог",
    isOnlineAvailable: true,
    rating: 4.6,
    reviews: 76,
    experience: 7,
    image: "https://pravatar.cc/300?img=29",
    education: "ОшГМА, 2017. Ординатура по дерматологии — Алматы.",
    about:
      "Лечение акне, псориаза, экземы, аллергических дерматитов. Косметологические процедуры.",
    workplaces: [
      {
        clinicId: "2",
        clinicName: "Клиника «Здоровье»",
        price: 1200,
        schedule: {
          mon: { start: "10:00", end: "18:00" },
          tue: { start: "10:00", end: "18:00" },
          wed: { start: "10:00", end: "18:00" },
          thu: { start: "10:00", end: "18:00" },
          fri: { start: "10:00", end: "17:00" },
          sat: null,
          sun: null,
          lunchBreak: { start: "13:00", end: "14:00" },
        },
      },
    ],
    skills: ["Дерматоскопия", "Криотерапия", "Лазерное лечение"],
    contacts: {
      schedule: "Пн–Пт: 10:00–18:00",
      phone: "+996 700 567 890",
      email: "dzhuma@zdorovye.kg",
    },
  },
  {
    id: "6",
    name: "Усубалиев Темирбек Айтматович",
    specialty: "Хирург",
    isOnlineAvailable: false,
    rating: 4.8,
    reviews: 95,
    experience: 18,
    image: "https://pravatar.cc/300?img=15",
    education:
      "КГМА, 2006. Ординатура по хирургии, 2008. Стажировка — Германия, 2015.",
    about:
      "Специализируется на лапароскопических операциях и абдоминальной хирургии. Более 2000 успешных операций.",
    workplaces: [
      {
        clinicId: "2",
        clinicName: "Клиника «Здоровье»",
        price: 2000,
        schedule: {
          mon: { start: "09:00", end: "16:00" },
          tue: { start: "09:00", end: "16:00" },
          wed: { start: "09:00", end: "16:00" },
          thu: null,
          fri: null,
          sat: null,
          sun: null,
          lunchBreak: { start: "12:30", end: "13:30" },
        },
      },
    ],
    skills: [
      "Лапароскопия",
      "Аппендэктомия",
      "Грыжесечение",
      "Холецистэктомия",
    ],
    contacts: {
      schedule: "Пн–Ср: 09:00–16:00",
      phone: "+996 700 678 901",
      email: "usubaliev@zdorovye.kg",
    },
  },
  {
    id: "7",
    name: "Рысбекова Залина Канатовна",
    specialty: "Гинеколог",
    isOnlineAvailable: true,
    rating: 4.9,
    reviews: 187,
    experience: 14,
    image: "https://pravatar.cc/300?img=44",
    education: "КГМА, 2010. Ординатура по акушерству и гинекологии, 2012.",
    about:
      "Ведение беременности, лечение гинекологических заболеваний, эндоскопические операции.",
    workplaces: [
      {
        clinicId: "2",
        clinicName: "Клиника «Здоровье»",
        price: 1300,
        schedule: {
          mon: { start: "09:00", end: "18:00" },
          tue: { start: "09:00", end: "18:00" },
          wed: null,
          thu: { start: "09:00", end: "18:00" },
          fri: { start: "09:00", end: "18:00" },
          sat: { start: "10:00", end: "14:00" },
          sun: null,
          lunchBreak: { start: "13:00", end: "14:00" },
        },
      },
    ],
    skills: ["УЗИ плода", "Кольпоскопия", "Гистероскопия", "КТГ"],
    contacts: {
      schedule: "Пн, Вт, Чт, Пт, Сб: 09:00–18:00",
      phone: "+996 700 789 012",
      email: "rysbekova@zdorovye.kg",
    },
  },
  {
    id: "8",
    name: "Карыбеков Азиз Болотович",
    specialty: "Офтальмолог",
    isOnlineAvailable: false,
    rating: 4.7,
    reviews: 112,
    experience: 9,
    image: "https://pravatar.cc/300?img=18",
    education: "КГМА, 2015. Ординатура по офтальмологии — Москва, 2017.",
    about:
      "Диагностика и лечение катаракты, глаукомы, миопии. Лазерная коррекция зрения.",
    workplaces: [
      {
        clinicId: "3",
        clinicName: "МЦ «Диамед»",
        price: 1100,
        schedule: {
          mon: { start: "09:00", end: "17:00" },
          tue: { start: "09:00", end: "17:00" },
          wed: { start: "09:00", end: "17:00" },
          thu: { start: "09:00", end: "17:00" },
          fri: { start: "09:00", end: "16:00" },
          sat: null,
          sun: null,
          lunchBreak: { start: "13:00", end: "14:00" },
        },
      },
    ],
    skills: ["Периметрия", "Тонометрия", "ОКТ", "Лазерная коррекция"],
    contacts: {
      schedule: "Пн–Пт: 09:00–17:00",
      phone: "+996 700 890 123",
      email: "karybekov@diamed.kg",
    },
  },
];

export const MOCK_CLINICS: ClinicListItem[] = [
  {
    id: "1",
    name: "МЦ «Медика»",
    rating: 4.8,
    reviews: 312,
    experience: 15,
    address: "г. Бишкек, ул. Московская, 127",
    city: "Бишкек",
    coordinates: { lat: 42.8746, lng: 74.602 },
    specialties: ["Кардиология", "Терапия", "Неврология", "Педиатрия"],
    image: "https://placehold.co/400x300/FEF3F0/F5653E?text=Medika",
    about:
      "Многопрофильная клиника с 15-летним опытом работы. Оснащена современным диагностическим оборудованием.",
    schedule: "Пн–Пт: 08:00–20:00, Сб: 09:00–16:00",
    phone: "+996 (312) 45-67-89",
    email: "info@medika.kg",
    images: [
      "https://placehold.co/800x500/E3E4E5/838A8D?text=Medika+Hall",
      "https://placehold.co/800x500/E3E4E5/838A8D?text=Medika+Lab",
    ],
    branches: [
      {
        id: "1-1",
        address: "г. Бишкек, ул. Ахунбаева, 92",
        phone: "+996 (312) 45-67-90",
        schedule: "Пн–Пт: 09:00–18:00",
        city: "Бишкек",
        coordinates: { lat: 42.858, lng: 74.619 },
      },
      {
        id: "1-2",
        address: "г. Бишкек, мкр. Джал, ул. Ибраимова, 34",
        phone: "+996 (312) 45-67-91",
        schedule: "Пн–Сб: 10:00–19:00",
        city: "Бишкек",
        coordinates: { lat: 42.845, lng: 74.61 },
      },
    ],
  },
  {
    id: "2",
    name: "Клиника «Здоровье»",
    rating: 4.6,
    reviews: 198,
    experience: 10,
    address: "г. Бишкек, пр. Манаса, 45",
    city: "Бишкек",
    coordinates: { lat: 42.8706, lng: 74.589 },
    specialties: ["Дерматология", "Гинекология", "Хирургия"],
    image: "https://placehold.co/400x300/F0FEF3/4CAF50?text=Zdorovye",
    about:
      "Специализированная клиника, сочетающая передовые методы диагностики и лечения.",
    schedule: "Пн–Сб: 09:00–19:00",
    phone: "+996 (312) 22-33-44",
    email: "info@zdorovye.kg",
    images: ["https://placehold.co/800x500/E3E4E5/838A8D?text=Zdorovye+Hall"],
    branches: [
      {
        id: "2-1",
        address: "г. Бишкек, ул. Фрунзе, 155",
        phone: "+996 (312) 22-33-45",
        schedule: "Пн–Сб: 09:00–18:00",
        city: "Бишкек",
        coordinates: { lat: 42.872, lng: 74.595 },
      },
    ],
  },
  {
    id: "3",
    name: "МЦ «Диамед»",
    rating: 4.7,
    reviews: 254,
    experience: 12,
    address: "г. Бишкек, ул. Токтогула, 78",
    city: "Бишкек",
    coordinates: { lat: 42.8695, lng: 74.601 },
    specialties: ["Офтальмология", "ЛОР", "Ортопедия"],
    image: "https://placehold.co/400x300/F0F4FE/3B82F6?text=Diamed",
    about:
      "Современный медицинский центр с уникальным оборудованием для офтальмологии и ЛОР-заболеваний.",
    schedule: "Пн–Пт: 08:30–19:30, Сб: 10:00–15:00",
    phone: "+996 (312) 55-66-77",
    email: "info@diamed.kg",
    images: [],
  },
  {
    id: "4",
    name: "МЦ «Жизнь»",
    rating: 4.9,
    reviews: 421,
    experience: 20,
    address: "г. Бишкек, ул. Чуй, 210",
    city: "Бишкек",
    coordinates: { lat: 42.872, lng: 74.595 },
    specialties: ["Кардиология", "Онкология", "Реабилитация", "Педиатрия"],
    image: "https://placehold.co/400x300/FFF8E1/FF9800?text=Life",
    about:
      "Флагманская клиника с 20-летней историей. Полный цикл медицинской помощи.",
    schedule: "Круглосуточно",
    phone: "+996 (312) 99-00-11",
    email: "info@zhizn.kg",
    images: [
      "https://placehold.co/800x500/E3E4E5/838A8D?text=Life+Main",
      "https://placehold.co/800x500/E3E4E5/838A8D?text=Life+ICU",
    ],
    branches: [
      {
        id: "4-1",
        address: "г. Бишкек, ул. Байтик Баатыра, 50",
        phone: "+996 (312) 99-00-12",
        schedule: "Пн–Пт: 08:00–20:00",
        city: "Бишкек",
        coordinates: { lat: 42.879, lng: 74.585 },
      },
      {
        id: "4-2",
        address: "г. Бишкек, мкр. Аламедин-1, д. 15",
        phone: "+996 (312) 99-00-13",
        schedule: "Круглосуточно",
        city: "Бишкек",
        coordinates: { lat: 42.882, lng: 74.63 },
      },
    ],
  },
];

export const MOCK_SERVICES: ServiceItem[] = [
  {
    id: "1",
    clinicId: "1",
    clinicName: "МЦ «Медика»",
    name: "ЭКГ с расшифровкой",
    category: "Кардиология",
    price: 800,
    image: "https://placehold.co/400x300/FEF3F0/F5653E?text=ECG",
    doctorIds: ["1", "2"],
    rating: 4.8,
    reviews: 45,
    schedule: {
      mon: { start: "09:00", end: "18:00" },
      tue: { start: "09:00", end: "18:00" },
      wed: { start: "09:00", end: "18:00" },
      thu: { start: "09:00", end: "18:00" },
      fri: { start: "09:00", end: "17:00" },
      sat: null,
      sun: null,
      lunchBreak: { start: "13:00", end: "14:00" },
    },
  },
  {
    id: "2",
    clinicId: "1",
    clinicName: "МЦ «Медика»",
    name: "Консультация невролога",
    category: "Неврология",
    price: 1400,
    image: "https://placehold.co/400x300/F0F4FE/3B82F6?text=Neuro",
    doctorIds: ["3"],
    rating: 4.9,
    reviews: 62,
    schedule: {
      mon: { start: "09:00", end: "17:00" },
      tue: null,
      wed: { start: "09:00", end: "17:00" },
      thu: null,
      fri: { start: "09:00", end: "17:00" },
      sat: null,
      sun: null,
      lunchBreak: { start: "13:00", end: "14:00" },
    },
  },
  {
    id: "3",
    clinicId: "2",
    clinicName: "Клиника «Здоровье»",
    name: "Приём дерматолога + дерматоскопия",
    category: "Дерматология",
    price: 1600,
    image: "https://placehold.co/400x300/F0FEF3/4CAF50?text=Derma",
    doctorIds: ["5"],
    rating: 4.7,
    reviews: 38,
    schedule: {
      mon: { start: "10:00", end: "18:00" },
      tue: { start: "10:00", end: "18:00" },
      wed: { start: "10:00", end: "18:00" },
      thu: { start: "10:00", end: "18:00" },
      fri: { start: "10:00", end: "17:00" },
      sat: null,
      sun: null,
      lunchBreak: { start: "13:00", end: "14:00" },
    },
  },
  {
    id: "4",
    clinicId: "2",
    clinicName: "Клиника «Здоровье»",
    name: "УЗИ органов малого таза",
    category: "Гинекология",
    price: 1200,
    image: "https://placehold.co/400x300/FFF8E1/FF9800?text=USG",
    doctorIds: ["7"],
    rating: 4.9,
    reviews: 91,
    schedule: {
      mon: { start: "09:00", end: "18:00" },
      tue: { start: "09:00", end: "18:00" },
      wed: null,
      thu: { start: "09:00", end: "18:00" },
      fri: { start: "09:00", end: "18:00" },
      sat: { start: "10:00", end: "14:00" },
      sun: null,
      lunchBreak: { start: "13:00", end: "14:00" },
    },
  },
  {
    id: "5",
    clinicId: "3",
    clinicName: "МЦ «Диамед»",
    name: "Проверка зрения + подбор очков",
    category: "Офтальмология",
    price: 900,
    image: "https://placehold.co/400x300/F0F4FE/6366F1?text=Eyes",
    doctorIds: ["8"],
    rating: 4.7,
    reviews: 54,
    schedule: {
      mon: { start: "09:00", end: "17:00" },
      tue: { start: "09:00", end: "17:00" },
      wed: { start: "09:00", end: "17:00" },
      thu: { start: "09:00", end: "17:00" },
      fri: { start: "09:00", end: "16:00" },
      sat: null,
      sun: null,
      lunchBreak: { start: "13:00", end: "14:00" },
    },
  },
  {
    id: "6",
    clinicId: "4",
    clinicName: "МЦ «Жизнь»",
    name: "Педиатрический осмотр (0–18 лет)",
    category: "Педиатрия",
    price: 1100,
    image: "https://placehold.co/400x300/FEF3F0/F5653E?text=Pediatrics",
    doctorIds: ["4"],
    rating: 4.9,
    reviews: 143,
    schedule: {
      mon: { start: "09:00", end: "18:00" },
      tue: { start: "09:00", end: "18:00" },
      wed: { start: "09:00", end: "18:00" },
      thu: { start: "09:00", end: "18:00" },
      fri: { start: "09:00", end: "17:00" },
      sat: { start: "10:00", end: "14:00" },
      sun: null,
      lunchBreak: { start: "13:00", end: "14:00" },
    },
  },
  {
    id: "7",
    clinicId: "1",
    clinicName: "МЦ «Медика»",
    name: "Суточное мониторирование АД (Холтер)",
    category: "Кардиология",
    price: 2500,
    image: "https://placehold.co/400x300/FEF3F0/F5653E?text=Holter",
    doctorIds: ["1"],
    rating: 4.8,
    reviews: 29,
    schedule: {
      mon: { start: "09:00", end: "16:00" },
      tue: { start: "09:00", end: "16:00" },
      wed: { start: "09:00", end: "16:00" },
      thu: { start: "09:00", end: "16:00" },
      fri: { start: "09:00", end: "15:00" },
      sat: null,
      sun: null,
      lunchBreak: null,
    },
  },
  {
    id: "8",
    clinicId: "4",
    clinicName: "МЦ «Жизнь»",
    name: "Консультация кардиолога онлайн",
    category: "Кардиология",
    price: 1200,
    image: "https://placehold.co/400x300/F0FEF3/4CAF50?text=Online",
    doctorIds: ["1"],
    rating: 4.8,
    reviews: 67,
    schedule: {
      mon: { start: "09:00", end: "20:00" },
      tue: { start: "09:00", end: "20:00" },
      wed: { start: "09:00", end: "20:00" },
      thu: { start: "09:00", end: "20:00" },
      fri: { start: "09:00", end: "20:00" },
      sat: { start: "10:00", end: "18:00" },
      sun: { start: "10:00", end: "18:00" },
      lunchBreak: null,
    },
  },
];

export const MOCK_REVIEWS: ReviewItem[] = [
  {
    id: "1",
    author: "Айнура К.",
    avatar: "https://pravatar.cc/80?img=5",
    date: "2026-04-10",
    text: "Отличный специалист! Очень внимательна, всё подробно объяснила. Назначенное лечение помогло быстро.",
    rating: 5,
    doctorId: "1",
    clinicId: "1",
  },
  {
    id: "2",
    author: "Бектур М.",
    avatar: "https://pravatar.cc/80?img=8",
    date: "2026-03-25",
    text: "Профессионал своего дела. Сразу поставила верный диагноз, хотя до этого несколько врачей не могли разобраться.",
    rating: 5,
    doctorId: "1",
    clinicId: "1",
  },
  {
    id: "3",
    author: "Гулим Т.",
    avatar: "https://pravatar.cc/80?img=9",
    date: "2026-04-15",
    text: "Марат Жапарович очень доступно объяснил ситуацию. Лечение назначил быстро и чётко.",
    rating: 5,
    doctorId: "2",
    clinicId: "1",
  },
  {
    id: "4",
    author: "Данияр С.",
    avatar: "https://pravatar.cc/80?img=11",
    date: "2026-03-30",
    text: "Хороший врач, но пришлось ждать очереди довольно долго. По качеству приёма претензий нет.",
    rating: 4,
    doctorId: "2",
    clinicId: "1",
  },
  {
    id: "5",
    author: "Жылдыз А.",
    avatar: "https://pravatar.cc/80?img=13",
    date: "2026-04-20",
    text: "Гульнара Турдуевна помогла мне с хроническими головными болями, которые мучили несколько лет. Огромное спасибо!",
    rating: 5,
    doctorId: "3",
    clinicId: "1",
  },
  {
    id: "6",
    author: "Каныбек Р.",
    avatar: "https://pravatar.cc/80?img=16",
    date: "2026-04-05",
    text: "Грамотный невролог. Назначила адекватное лечение, без лишних анализов.",
    rating: 5,
    doctorId: "3",
    clinicId: "1",
  },
  {
    id: "7",
    author: "Лейла Н.",
    avatar: "https://pravatar.cc/80?img=20",
    date: "2026-04-18",
    text: "Бакыт Эркинович — лучший детский врач! Нашему сыну было 3 месяца, он осмотрел очень бережно и профессионально.",
    rating: 5,
    doctorId: "4",
    clinicId: "4",
  },
  {
    id: "8",
    author: "Манас Ж.",
    avatar: "https://pravatar.cc/80?img=22",
    date: "2026-03-15",
    text: "Очень терпеливый с детьми. Дочка перестала бояться врачей после его приёма.",
    rating: 5,
    doctorId: "4",
    clinicId: "4",
  },
  {
    id: "9",
    author: "Нурзат Б.",
    avatar: "https://pravatar.cc/80?img=26",
    date: "2026-04-12",
    text: "Анара Сатыбековна помогла с акне за несколько месяцев. Теперь кожа чистая, рада что обратилась.",
    rating: 5,
    doctorId: "5",
    clinicId: "2",
  },
  {
    id: "10",
    author: "Омурбек Т.",
    avatar: "https://pravatar.cc/80?img=28",
    date: "2026-03-22",
    text: "Хорошая клиника, доктор внимательная. Единственный минус — запись только за неделю вперёд.",
    rating: 4,
    doctorId: "5",
    clinicId: "2",
  },
  {
    id: "11",
    author: "Перизат С.",
    avatar: "https://pravatar.cc/80?img=31",
    date: "2026-04-08",
    text: "Темирбек Айтматович провёл операцию великолепно. Восстановление прошло быстро, осложнений не было.",
    rating: 5,
    doctorId: "6",
    clinicId: "2",
  },
  {
    id: "12",
    author: "Руслан К.",
    avatar: "https://pravatar.cc/80?img=35",
    date: "2026-03-18",
    text: "Профессиональный хирург с золотыми руками. Рекомендую всем кто нуждается в операции.",
    rating: 5,
    doctorId: "6",
    clinicId: "2",
  },
  {
    id: "13",
    author: "Сезим А.",
    avatar: "https://pravatar.cc/80?img=38",
    date: "2026-04-22",
    text: "Залина Канатовна вела мою беременность с 8 недель. Всегда на связи, очень заботливый доктор.",
    rating: 5,
    doctorId: "7",
    clinicId: "2",
  },
  {
    id: "14",
    author: "Тилек Ж.",
    avatar: "https://pravatar.cc/80?img=41",
    date: "2026-04-02",
    text: "Хороший специалист. Всё объяснила, дала рекомендации. Буду обращаться снова.",
    rating: 4,
    doctorId: "7",
    clinicId: "2",
  },
  {
    id: "15",
    author: "Улан М.",
    avatar: "https://pravatar.cc/80?img=43",
    date: "2026-04-14",
    text: "Азиз Болотович подобрал правильные линзы после долгих мучений. Зрение отличное, спасибо!",
    rating: 5,
    doctorId: "8",
    clinicId: "3",
  },
  {
    id: "16",
    author: "Чолпон Э.",
    avatar: "https://pravatar.cc/80?img=46",
    date: "2026-03-28",
    text: "Внимательный офтальмолог. Провёл полное обследование, объяснил всё понятно.",
    rating: 5,
    doctorId: "8",
    clinicId: "3",
  },
];
